#spring.application.name=ms-ventas-service
spring:
  application:
    name: ms-ventas-service
  profiles:
    active: development
  config:
    import: optional:configserver:http://root:password@localhost:7070