spring:
  application:
    name: ms-catalogo-service
  profiles:
    active: development
  config:
    import: optional:configserver:http://root:password@localhost:7070

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10  # Intervalo para enviar heartbeats a Eureka
    leaseExpirationDurationInSeconds: 30